<?php

namespace Projet\ForumBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends \Doctrine\ORM\EntityRepository
{
	public function getOrderedThemes(){
		return $this->createQueryBuilder('t')
			->orderBy('t.id')
			->getQuery()
      		->getResult()
      	;
	}
}
