Projet\UserBundle\Entity\User:
    properties:
        username:
            - NotBlank:
                message: fos_user.username.blank
            - Length:
                min: 2
                max: 30
                minMessage: fos_user.username.short
                maxMessage: fos_user.username.long
                groups: [Registration,Profile]